// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/profile-service/proto/profile.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Photo struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccessUrl            string   `protobuf:"bytes,2,opt,name=accessUrl,proto3" json:"accessUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac222d222dbc9886, []int{0}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Photo) GetAccessUrl() string {
	if m != nil {
		return m.AccessUrl
	}
	return ""
}

type Profile struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int64    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  string   `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Complexion           string   `protobuf:"bytes,5,opt,name=complexion,proto3" json:"complexion,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,6,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	IgUsername           string   `protobuf:"bytes,7,opt,name=igUsername,proto3" json:"igUsername,omitempty"`
	TwitterUsername      string   `protobuf:"bytes,8,opt,name=twitterUsername,proto3" json:"twitterUsername,omitempty"`
	Location             string   `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	About                string   `protobuf:"bytes,10,opt,name=about,proto3" json:"about,omitempty"`
	PartnerDescription   string   `protobuf:"bytes,11,opt,name=partnerDescription,proto3" json:"partnerDescription,omitempty"`
	AdditionalInfo       string   `protobuf:"bytes,12,opt,name=additionalInfo,proto3" json:"additionalInfo,omitempty"`
	Photos               []*Photo `protobuf:"bytes,13,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac222d222dbc9886, []int{1}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Profile) GetSex() string {
	if m != nil {
		return m.Sex
	}
	return ""
}

func (m *Profile) GetComplexion() string {
	if m != nil {
		return m.Complexion
	}
	return ""
}

func (m *Profile) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile) GetIgUsername() string {
	if m != nil {
		return m.IgUsername
	}
	return ""
}

func (m *Profile) GetTwitterUsername() string {
	if m != nil {
		return m.TwitterUsername
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Profile) GetPartnerDescription() string {
	if m != nil {
		return m.PartnerDescription
	}
	return ""
}

func (m *Profile) GetAdditionalInfo() string {
	if m != nil {
		return m.AdditionalInfo
	}
	return ""
}

func (m *Profile) GetPhotos() []*Photo {
	if m != nil {
		return m.Photos
	}
	return nil
}

type CreateProfileRequest struct {
	Data                 *Profile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProfileRequest) Reset()         { *m = CreateProfileRequest{} }
func (m *CreateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProfileRequest) ProtoMessage()    {}
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac222d222dbc9886, []int{2}
}

func (m *CreateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileRequest.Unmarshal(m, b)
}
func (m *CreateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileRequest.Merge(m, src)
}
func (m *CreateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProfileRequest.Size(m)
}
func (m *CreateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileRequest proto.InternalMessageInfo

func (m *CreateProfileRequest) GetData() *Profile {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateProfileResponse struct {
	Data                 *Profile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProfileResponse) Reset()         { *m = CreateProfileResponse{} }
func (m *CreateProfileResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProfileResponse) ProtoMessage()    {}
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac222d222dbc9886, []int{3}
}

func (m *CreateProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProfileResponse.Unmarshal(m, b)
}
func (m *CreateProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProfileResponse.Marshal(b, m, deterministic)
}
func (m *CreateProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProfileResponse.Merge(m, src)
}
func (m *CreateProfileResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProfileResponse.Size(m)
}
func (m *CreateProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProfileResponse proto.InternalMessageInfo

func (m *CreateProfileResponse) GetData() *Profile {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Photo)(nil), "pb.Photo")
	proto.RegisterType((*Profile)(nil), "pb.Profile")
	proto.RegisterType((*CreateProfileRequest)(nil), "pb.CreateProfileRequest")
	proto.RegisterType((*CreateProfileResponse)(nil), "pb.CreateProfileResponse")
}

func init() {
	proto.RegisterFile("src/profile-service/proto/profile.proto", fileDescriptor_ac222d222dbc9886)
}

var fileDescriptor_ac222d222dbc9886 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0xcb, 0xd3, 0x40,
	0x10, 0xc6, 0xed, 0x9b, 0xfe, 0xcb, 0xc4, 0x56, 0x59, 0x2a, 0xac, 0x45, 0x34, 0xe6, 0xa0, 0xb9,
	0x18, 0xa1, 0x1e, 0xf4, 0x5e, 0x11, 0x7a, 0x91, 0x12, 0x29, 0x78, 0xdd, 0x24, 0xd3, 0x36, 0x90,
	0x66, 0xd7, 0xdd, 0x8d, 0xf6, 0xa3, 0xf8, 0x71, 0x65, 0x27, 0xb1, 0xed, 0x5b, 0x0a, 0xbd, 0xcd,
	0xfc, 0x9e, 0x67, 0x9e, 0x5d, 0x98, 0x81, 0xf7, 0x46, 0xe7, 0x1f, 0x95, 0x96, 0xdb, 0xb2, 0xc2,
	0x0f, 0x06, 0xf5, 0xef, 0x32, 0x47, 0xd7, 0x5b, 0xf9, 0x9f, 0x26, 0xd4, 0xb1, 0x07, 0x95, 0x45,
	0x4b, 0x18, 0xac, 0xf7, 0xae, 0x79, 0x05, 0xbe, 0xc8, 0x73, 0xd9, 0xd4, 0x76, 0x55, 0xf0, 0x5e,
	0xd8, 0x8b, 0xbd, 0xf4, 0x0c, 0x3a, 0x15, 0x8d, 0xd9, 0xe8, 0x8a, 0x3f, 0x84, 0xbd, 0xd8, 0x4f,
	0xcf, 0x20, 0xfa, 0xeb, 0xc1, 0x68, 0xdd, 0x46, 0xdf, 0xc9, 0x61, 0xd0, 0xaf, 0xc5, 0x01, 0xbb,
	0x08, 0xaa, 0xd9, 0x73, 0xf0, 0xc4, 0x0e, 0xb9, 0x47, 0x5e, 0x57, 0x3a, 0x62, 0xf0, 0xc8, 0xfb,
	0x64, 0x72, 0x25, 0x7b, 0x0d, 0x90, 0xcb, 0x83, 0xaa, 0xf0, 0x58, 0xca, 0x9a, 0x0f, 0x48, 0xb8,
	0x20, 0x2c, 0x84, 0x40, 0xed, 0x65, 0x8d, 0xdf, 0x9b, 0x43, 0x86, 0x9a, 0x0f, 0xc9, 0x70, 0x89,
	0x5c, 0x42, 0xb9, 0xdb, 0x18, 0xd4, 0xf4, 0xfe, 0xa8, 0x4d, 0x38, 0x13, 0x16, 0xc3, 0x33, 0xfb,
	0xa7, 0xb4, 0x16, 0xf5, 0xc9, 0x34, 0x26, 0xd3, 0x35, 0x66, 0x73, 0x18, 0x57, 0x32, 0x17, 0xd6,
	0xfd, 0xc4, 0x27, 0xcb, 0xa9, 0x67, 0x33, 0x18, 0x88, 0x4c, 0x36, 0x96, 0x03, 0x09, 0x6d, 0xc3,
	0x12, 0x60, 0x4a, 0x68, 0x5b, 0xa3, 0xfe, 0x8a, 0x26, 0xd7, 0xa5, 0xa2, 0xd9, 0x80, 0x2c, 0x37,
	0x14, 0xf6, 0x0e, 0xa6, 0xa2, 0x28, 0x4a, 0x57, 0x8b, 0x6a, 0x55, 0x6f, 0x25, 0x7f, 0x4a, 0xde,
	0x2b, 0xca, 0xde, 0xc2, 0x50, 0xb9, 0xe5, 0x19, 0x3e, 0x09, 0xbd, 0x38, 0x58, 0xf8, 0x89, 0xca,
	0x12, 0x5a, 0x67, 0xda, 0x09, 0xd1, 0x67, 0x98, 0x2d, 0x35, 0x0a, 0x8b, 0xdd, 0x7e, 0x52, 0xfc,
	0xd5, 0xa0, 0xb1, 0xec, 0x0d, 0xf4, 0x0b, 0x61, 0x05, 0x6d, 0x28, 0x58, 0x04, 0x34, 0xd8, 0x39,
	0x48, 0x88, 0xbe, 0xc0, 0x8b, 0xab, 0x41, 0xa3, 0x64, 0x6d, 0xf0, 0xee, 0xe4, 0xe2, 0x27, 0x4c,
	0x3b, 0xf0, 0xa3, 0x3d, 0x3e, 0xf6, 0x0d, 0x26, 0x8f, 0xb2, 0x18, 0x77, 0x53, 0xb7, 0xfe, 0x35,
	0x7f, 0x79, 0x43, 0x69, 0x1f, 0x8e, 0x9e, 0x64, 0x43, 0xba, 0xdb, 0x4f, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0x49, 0x7d, 0x01, 0xe2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, "/pb.ProfileService/CreateProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) CreateProfile(ctx context.Context, req *CreateProfileRequest) (*CreateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ProfileService/CreateProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _ProfileService_CreateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/profile-service/proto/profile.proto",
}
